import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Explicit rather than autogenerated: the reading order is an editorial
 * decision, and a new file should not silently appear in the middle of it.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'pg_describe',
      collapsed: false,
      items: ['overview', 'features', 'getting-started', 'installation'],
    },
    {
      type: 'category',
      label: 'TypeScript',
      collapsed: false,
      items: [
        'end-to-end-example',
        'queries-in-sql-files',
        'generated-code',
        'cli-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Typing',
      collapsed: false,
      items: ['nullability', 'type-mapping'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: ['function-reference', 'permissions', 'how-it-works'],
    },
    {
      type: 'category',
      label: 'Project',
      collapsed: false,
      items: ['contributing', 'credit'],
    },
  ],
}

export default sidebars
